using Microsoft.EntityFrameworkCore.Migrations;

namespace hub.Server.Migrations
{
    public partial class switchtoautogenerateduserid : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
